services:
  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - proxy

  mealie:
    image: ghcr.io/mealie-recipes/mealie:v3.22.0
    restart: unless-stopped

    volumes:
      - mealie_data:/app/data

    environment:
      ALLOW_SIGNUP: "false"
      PUID: 1000
      PGID: 1000
      TZ: Europe/Berlin
      BASE_URL: https://mealie.home.antonu.org

    networks:
      - proxy

networks:
  proxy:

volumes:
  caddy_data:
  caddy_config:
  mealie_data:
    external: true
    name: pi-mealie_mealie-data
